-- ============================================================
-- Unified Contact Model Refactor (Final State)
-- ============================================================
-- Purpose:
--   Consolidate primary contact model from split PrimaryAddressID +
--   PrimaryPhoneContactID into single PrimaryContactID FK pointing
--   to new unified Contact table (wrapping address/phone/email/url types).
--   Adds privacy flags; seeds LinkCategory hierarchy; unifies form metadata.
--
-- Safety:
--   - All DDL is idempotent (IF NOT EXISTS)
--   - All operations wrapped in transactions
--   - Backfill uses safe conditional logic
--   - Legacy columns preserved until final cleanup
--
-- Scope:
--   - Applies to Artists, Users, Vendors, Venues
--   - Venue preserves legacy AddressID + PhoneContactID for backward compat
--   - Artist, User, Vendor retire split primary columns
--
-- ============================================================

-- ============================================================
-- Phase 1: Phone Contact Infrastructure
-- ============================================================

CREATE TABLE IF NOT EXISTS "PhoneContactLabels" (
	"PhoneContactLabelID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"Label" varchar(50) NOT NULL,
	CONSTRAINT "AK_PhoneContactLabels_Label" UNIQUE ("Label")
);

INSERT INTO "PhoneContactLabels" ("PhoneContactLabelID", "Label")
VALUES
	(1, 'home'),
	(2, 'office'),
	(3, 'mobile'),
	(4, 'other')
ON CONFLICT ("PhoneContactLabelID") DO NOTHING;

-- Add PhoneContactLabelID column and FK to PhoneContacts (idempotent).
ALTER TABLE "PhoneContacts"
	ADD COLUMN IF NOT EXISTS "PhoneContactLabelID" integer;

-- Backfill NULL values with default label (office).
UPDATE "PhoneContacts"
SET "PhoneContactLabelID" = 2
WHERE "PhoneContactLabelID" IS NULL;

-- Finalize column: NOT NULL, DEFAULT 2.
ALTER TABLE "PhoneContacts"
	ALTER COLUMN "PhoneContactLabelID" SET DEFAULT 2;

ALTER TABLE "PhoneContacts"
	ALTER COLUMN "PhoneContactLabelID" SET NOT NULL;

-- Add FK constraint (idempotent).
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'FK_PhoneContacts_PhoneContactLabels_PhoneContactLabelID') THEN
		ALTER TABLE "PhoneContacts"
			ADD CONSTRAINT "FK_PhoneContacts_PhoneContactLabels_PhoneContactLabelID"
			FOREIGN KEY ("PhoneContactLabelID") REFERENCES "PhoneContactLabels" ("PhoneContactLabelID")
			ON DELETE RESTRICT;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_PhoneContacts_PhoneContactLabelID"
	ON "PhoneContacts" ("PhoneContactLabelID");

CREATE TABLE IF NOT EXISTS "Contacts" (
	"ContactID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"ContactType" varchar(32) NOT NULL,
	"Label" varchar(100),
	"Category" varchar(100),
	"Value" varchar(1000),
	"Handle" varchar(255),
	"Description" varchar(255),
	"AddressID" integer,
	"PhoneContactID" integer,
	CONSTRAINT "FK_Contacts_Addresses_AddressID"
		FOREIGN KEY ("AddressID") REFERENCES "Addresses" ("AddressID") ON DELETE RESTRICT,
	CONSTRAINT "FK_Contacts_PhoneContacts_PhoneContactID"
		FOREIGN KEY ("PhoneContactID") REFERENCES "PhoneContacts" ("PhoneContactID") ON DELETE RESTRICT,
	CONSTRAINT "CK_Contacts_ContactType" CHECK ("ContactType" IN ('address', 'phone', 'email', 'url')),
	CONSTRAINT "CK_Contacts_TypePayload" CHECK (
		("ContactType" = 'address' AND "AddressID" IS NOT NULL AND "PhoneContactID" IS NULL AND "Value" IS NULL) OR
		("ContactType" = 'phone' AND "PhoneContactID" IS NOT NULL AND "AddressID" IS NULL AND "Value" IS NULL) OR
		("ContactType" = 'email' AND "Value" IS NOT NULL AND "AddressID" IS NULL AND "PhoneContactID" IS NULL) OR
		("ContactType" = 'url' AND "Value" IS NOT NULL AND "AddressID" IS NULL AND "PhoneContactID" IS NULL)
	)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Contacts_AddressID"
	ON "Contacts" ("AddressID")
	WHERE "AddressID" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Contacts_PhoneContactID"
	ON "Contacts" ("PhoneContactID")
	WHERE "PhoneContactID" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "Linker_EntityToContacts" (
	"Linker_EntityToContactID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"ContactID" integer NOT NULL,
	"UserID" integer,
	"ArtistID" integer,
	"VenueID" integer,
	"VendorID" integer,
	"MakePublic" boolean NOT NULL DEFAULT FALSE,
	"DisplayOrder" integer NOT NULL DEFAULT 0,
	CONSTRAINT "FK_LinkerEntityToContacts_Contacts_ContactID"
		FOREIGN KEY ("ContactID") REFERENCES "Contacts" ("ContactID") ON DELETE CASCADE,
	CONSTRAINT "FK_LinkerEntityToContacts_Users_UserID"
		FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE RESTRICT,
	CONSTRAINT "FK_LinkerEntityToContacts_Artists_ArtistID"
		FOREIGN KEY ("ArtistID") REFERENCES "Artists" ("ArtistID") ON DELETE RESTRICT,
	CONSTRAINT "FK_LinkerEntityToContacts_Venues_VenueID"
		FOREIGN KEY ("VenueID") REFERENCES "Venues" ("VenueID") ON DELETE RESTRICT,
	CONSTRAINT "FK_LinkerEntityToContacts_Vendors_VendorID"
		FOREIGN KEY ("VendorID") REFERENCES "Vendors" ("VendorID") ON DELETE RESTRICT,
	CONSTRAINT "CK_LinkerEntityToContact_SingleOwner"
		CHECK (
			(CASE WHEN "UserID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "ArtistID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "VenueID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "VendorID" IS NOT NULL THEN 1 ELSE 0 END) = 1
		)
);

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_ContactID"
	ON "Linker_EntityToContacts" ("ContactID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_UserID"
	ON "Linker_EntityToContacts" ("UserID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_ArtistID"
	ON "Linker_EntityToContacts" ("ArtistID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_VenueID"
	ON "Linker_EntityToContacts" ("VenueID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_VendorID"
	ON "Linker_EntityToContacts" ("VendorID");

ALTER TABLE "Linker_EntityToContacts"
	DROP COLUMN IF EXISTS "IsPrimary";

-- ============================================================
-- Phase 2: Privacy Flags
-- ============================================================
-- Add IsPrivate boolean to core contact entities.
-- Default: false (public).

ALTER TABLE "PhoneContacts"
	ADD COLUMN IF NOT EXISTS "IsPrivate" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Addresses"
	ADD COLUMN IF NOT EXISTS "IsPrivate" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Contacts"
	ADD COLUMN IF NOT EXISTS "IsPrivate" boolean NOT NULL DEFAULT FALSE;

-- ============================================================
-- Phase 3: Unified Contact Table
-- ============================================================
-- Wraps address/phone/email/url types with type-specific FKs.
-- Enforces single-payload constraint: each contact type has exactly one payload.

CREATE TABLE IF NOT EXISTS "Contacts" (
	"ContactID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"ContactType" varchar(32) NOT NULL,
	"Label" varchar(100),
	"Category" varchar(100),
	"Value" varchar(1000),
	"Handle" varchar(255),
	"Description" varchar(255),
	"AddressID" integer,
	"PhoneContactID" integer,
	"IsPrivate" boolean NOT NULL DEFAULT FALSE,
	CONSTRAINT "FK_Contacts_Addresses_AddressID"
		FOREIGN KEY ("AddressID") REFERENCES "Addresses" ("AddressID") ON DELETE RESTRICT,
	CONSTRAINT "FK_Contacts_PhoneContacts_PhoneContactID"
		FOREIGN KEY ("PhoneContactID") REFERENCES "PhoneContacts" ("PhoneContactID") ON DELETE RESTRICT,
	CONSTRAINT "CK_Contacts_ContactType"
		CHECK ("ContactType" IN ('address', 'phone', 'email', 'url')),
	CONSTRAINT "CK_Contacts_TypePayload"
		CHECK (
			("ContactType" = 'address' AND "AddressID" IS NOT NULL AND "PhoneContactID" IS NULL AND "Value" IS NULL) OR
			("ContactType" = 'phone' AND "PhoneContactID" IS NOT NULL AND "AddressID" IS NULL AND "Value" IS NULL) OR
			("ContactType" = 'email' AND "Value" IS NOT NULL AND "AddressID" IS NULL AND "PhoneContactID" IS NULL) OR
			("ContactType" = 'url' AND "Value" IS NOT NULL AND "AddressID" IS NULL AND "PhoneContactID" IS NULL)
		)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Contacts_AddressID"
	ON "Contacts" ("AddressID")
	WHERE "AddressID" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Contacts_PhoneContactID"
	ON "Contacts" ("PhoneContactID")
	WHERE "PhoneContactID" IS NOT NULL;

-- ============================================================
-- Phase 4: Linker Entity-To-Contact
-- ============================================================
-- Junction table linking entities (Artist, User, Venue, Vendor)
-- to their contacts. Supports display order and public visibility.
-- Check constraint ensures exactly one owner entity per link.

CREATE TABLE IF NOT EXISTS "Linker_EntityToContacts" (
	"Linker_EntityToContactID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"ContactID" integer NOT NULL,
	"UserID" integer,
	"ArtistID" integer,
	"VenueID" integer,
	"VendorID" integer,
	"MakePublic" boolean NOT NULL DEFAULT FALSE,
	"DisplayOrder" integer NOT NULL DEFAULT 0,
	CONSTRAINT "FK_LinkerEntityToContacts_Contacts_ContactID"
		FOREIGN KEY ("ContactID") REFERENCES "Contacts" ("ContactID") ON DELETE CASCADE,
	CONSTRAINT "FK_LinkerEntityToContacts_Users_UserID"
		FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE RESTRICT,
	CONSTRAINT "FK_LinkerEntityToContacts_Artists_ArtistID"
		FOREIGN KEY ("ArtistID") REFERENCES "Artists" ("ArtistID") ON DELETE RESTRICT,
	CONSTRAINT "FK_LinkerEntityToContacts_Venues_VenueID"
		FOREIGN KEY ("VenueID") REFERENCES "Venues" ("VenueID") ON DELETE RESTRICT,
	CONSTRAINT "FK_LinkerEntityToContacts_Vendors_VendorID"
		FOREIGN KEY ("VendorID") REFERENCES "Vendors" ("VendorID") ON DELETE RESTRICT,
	CONSTRAINT "CK_LinkerEntityToContact_SingleOwner"
		CHECK (
			(CASE WHEN "UserID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "ArtistID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "VenueID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "VendorID" IS NOT NULL THEN 1 ELSE 0 END) = 1
		)
);

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_ContactID"
	ON "Linker_EntityToContacts" ("ContactID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_UserID"
	ON "Linker_EntityToContacts" ("UserID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_ArtistID"
	ON "Linker_EntityToContacts" ("ArtistID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_VenueID"
	ON "Linker_EntityToContacts" ("VenueID");

CREATE INDEX IF NOT EXISTS "IX_Linker_EntityToContacts_VendorID"
	ON "Linker_EntityToContacts" ("VendorID");

-- Idempotent cleanup: remove any legacy IsPrimary column if present.
ALTER TABLE "Linker_EntityToContacts"
	DROP COLUMN IF EXISTS "IsPrimary";

-- ============================================================
-- Phase 4.5: Link Categories (Three-Level Hierarchy)
-- ============================================================
-- Hierarchical categorization for external links.
-- Levels: 1) Meta-groups (7) → 2) Sections (13) → 3) Platforms (59).

CREATE TABLE IF NOT EXISTS "LinkCategories" (
	"LinkCategoryID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"Category"             varchar(100) NOT NULL,
	"CategoryKey"          varchar(50)  NOT NULL,
	"Description"          varchar(255),
	"Tags"                 varchar(255),
	"ParentLinkCategoryID" integer,
	CONSTRAINT "AK_LinkCategories_CategoryKey" UNIQUE ("CategoryKey"),
	CONSTRAINT "FK_LinkCategories_LinkCategories_ParentLinkCategoryID"
		FOREIGN KEY ("ParentLinkCategoryID") REFERENCES "LinkCategories" ("LinkCategoryID")
		ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_LinkCategories_ParentLinkCategoryID"
	ON "LinkCategories" ("ParentLinkCategoryID");

-- Level 1: Meta Groups
INSERT INTO "LinkCategories" ("LinkCategoryID", "Category", "CategoryKey", "Description", "Tags", "ParentLinkCategoryID")
VALUES
	(1,  'Social',  'meta_social',  'Social presence and identity links.',              'meta, social',  NULL),
	(2,  'Create',  'meta_create',  'Creative platforms and development tools.',         'meta, create',  NULL),
	(3,  'Watch',   'meta_watch',   'Video, streaming, and interactive media.',          'meta, watch',   NULL),
	(4,  'Listen',  'meta_listen',  'Music, audio, and podcast platforms.',              'meta, listen',  NULL),
	(5,  'Shop',    'meta_shop',    'Storefronts and commerce destinations.',            'meta, shop',    NULL),
	(6,  'Support', 'meta_support', 'Payment and fan-support platforms.',                'meta, support', NULL),
	(7,  'Connect', 'meta_connect', 'Events, messaging, and professional connections.', 'meta, connect', NULL)
ON CONFLICT ("LinkCategoryID") DO NOTHING;

-- Level 2: Sections
INSERT INTO "LinkCategories" ("LinkCategoryID", "Category", "CategoryKey", "Description", "Tags", "ParentLinkCategoryID")
VALUES
	(8,  'General / Identity',      'general_identity',      'Personal and portfolio landing pages.',           'identity, profile',  1),
	(9,  'Social Media',            'social_media',          'Major social networking platforms.',              'social',             1),
	(10, 'Creative Platforms',      'creative_platforms',    'Portfolio and creative showcase sites.',          'create, portfolio',  2),
	(11, 'Content & Media',         'content_media',         'Video, streaming, and blog platforms.',           'watch, content',     3),
	(12, 'Music & Audio',           'music_audio',           'Music streaming and distribution.',               'listen, music',      4),
	(13, 'Storefronts & Commerce',  'storefronts_commerce',  'Online shop and marketplace platforms.',          'shop, ecommerce',    5),
	(14, 'Payments & Support',      'payments_support',      'Payment processors and fan support.',             'support, payments',  6),
	(15, 'Events & Ticketing',      'events_ticketing',      'Event listings and ticket sales.',                'connect, events',    7),
	(16, 'Professional / Business', 'professional_business', 'Professional presence and credentials.',          'connect, business',  7),
	(17, 'Messaging & Communities', 'messaging_communities', 'Direct messaging and group platforms.',           'connect, messaging', 7),
	(18, 'Developer / Technical',   'developer_technical',   'Code repositories and dev tools.',                'create, dev',        2),
	(19, 'Publications & Writing',  'publications_writing',  'Long-form writing and newsletters.',              'create, writing',    2),
	(20, 'Games & Interactive',     'games_interactive',     'Gaming storefronts and interactive platforms.',   'watch, games',       3)
ON CONFLICT ("LinkCategoryID") DO NOTHING;

-- Level 3: Individual Platforms
INSERT INTO "LinkCategories" ("LinkCategoryID", "Category", "CategoryKey", "Description", "Tags", "ParentLinkCategoryID")
VALUES
	(21, 'Personal Website',    'personal_website', 'Your own domain or custom personal site.',             'website, personal',   8),
	(22, 'Portfolio',           'portfolio',        'Curated showcase of your work.',                       'portfolio',           8),
	(23, 'Link Hub',            'link_hub',         'Linktree-style aggregator of all your links.',         'linktree, hub',       8),
	(24, 'Instagram',   'instagram',  'Photo and video social platform.',                   'instagram, social',   9),
	(25, 'TikTok',      'tiktok',     'Short-form video platform.',                         'tiktok, social',      9),
	(26, 'Twitter / X', 'twitter_x',  'Microblogging and public conversation platform.',    'twitter, x, social',  9),
	(27, 'Facebook',    'facebook',   'General-purpose social networking platform.',        'facebook, social',    9),
	(28, 'Snapchat',    'snapchat',   'Ephemeral photo and video messaging app.',           'snapchat, social',    9),
	(29, 'Threads',     'threads',    'Meta''s text-based social platform.',                'threads, social',     9),
	(30, 'Mastodon',    'mastodon',   'Decentralized open-source social network.',          'mastodon, fediverse', 9),
	(31, 'Behance',    'behance',    'Adobe''s creative portfolio network.',                'behance, portfolio', 10),
	(32, 'ArtStation', 'artstation', 'Portfolio platform for game, film, and media artists.','artstation',        10),
	(33, 'Dribbble',   'dribbble',   'Design community for UI, graphic, and web designers.','dribbble, design',  10),
	(34, 'DeviantArt', 'deviantart', 'Online art community for fan art and original works.', 'deviantart',        10),
	(35, 'Pixiv',      'pixiv',      'Japanese illustration and manga community.',           'pixiv, illustration',10),
	(36, 'YouTube', 'youtube', 'Video hosting and streaming platform.',    'youtube, video',    11),
	(37, 'Vimeo',   'vimeo',   'High-quality video hosting for creators.', 'vimeo, video',      11),
	(38, 'Twitch',  'twitch',  'Live streaming platform.',                 'twitch, streaming', 11),
	(39, 'Podcast', 'podcast', 'Audio podcast feed or hosting page.',      'podcast, audio',    11),
	(40, 'Blog',    'blog',    'Personal or professional blog.',           'blog, writing',     11),
	(41, 'Spotify',     'spotify',     'Music and podcast streaming platform.',        'spotify, music',    12),
	(42, 'SoundCloud',  'soundcloud',  'Audio distribution and discovery platform.',  'soundcloud, music', 12),
	(43, 'Apple Music', 'apple_music', 'Apple''s music streaming service.',            'applemusic, music', 12),
	(44, 'Bandcamp',    'bandcamp',    'Direct music sales and fan-support platform.', 'bandcamp, music',   12),
	(45, 'Mixcloud',    'mixcloud',    'DJ mixes, radio shows, and podcasts.',         'mixcloud, dj',      12),
	(46, 'Shopify',     'shopify',     'Full-featured ecommerce platform.',             'shopify, ecommerce', 13),
	(47, 'Etsy',        'etsy',        'Marketplace for handmade and vintage goods.',   'etsy, shop',         13),
	(48, 'BigCartel',   'bigcartel',   'Simple storefronts for artists and makers.',    'bigcartel, shop',    13),
	(49, 'Gumroad',     'gumroad',     'Digital products and creator commerce.',        'gumroad, digital',   13),
	(50, 'WooCommerce', 'woocommerce', 'WordPress-based ecommerce solution.',           'woocommerce, shop',  13),
	(51, 'PayPal',          'paypal',          'Online payment transfer service.',           'paypal, payments',   14),
	(52, 'Venmo',           'venmo',           'Mobile peer-to-peer payments.',              'venmo, payments',    14),
	(53, 'Cash App',        'cash_app',        'Mobile money transfer app.',                 'cashapp, payments',  14),
	(54, 'Zelle',           'zelle',           'Bank-integrated money transfer network.',    'zelle, payments',    14),
	(55, 'Stripe',          'stripe',          'Developer-friendly payment processing.',     'stripe, payments',   14),
	(56, 'Square',          'square',          'Payment processing and POS platform.',       'square, payments',   14),
	(57, 'Patreon',         'patreon',         'Recurring fan membership and support.',      'patreon, support',   14),
	(58, 'Ko-fi',           'kofi',            'One-time or recurring creator support.',     'kofi, support',      14),
	(59, 'Buy Me a Coffee', 'buy_me_a_coffee', 'Micro-donation and supporter platform.',     'bmac, support',      14),
	(60, 'Eventbrite',     'eventbrite',     'Event creation and ticket sales platform.', 'eventbrite, events', 15),
	(61, 'Ticketing Page', 'ticketing_page', 'Custom or third-party ticketing page.',     'tickets, events',    15),
	(62, 'Booking Page',   'booking_page',   'Scheduling or booking appointment page.',   'booking, events',    15),
	(63, 'LinkedIn',              'linkedin',        'Professional networking platform.',                 'linkedin, professional', 16),
	(64, 'Resume / CV',           'resume_cv',       'Downloadable or hosted resume or CV.',              'resume, cv',             16),
	(65, 'Press Kit',             'press_kit',       'Media and press kit for professional outreach.',    'presskit, epk',          16),
	(66, 'Booking / Contact Page','booking_contact', 'Page for booking inquiries or professional contact.','booking, contact',      16),
	(67, 'Discord',  'discord',  'Community server or direct invite link.',  'discord, community',  17),
	(68, 'Telegram', 'telegram', 'Messaging app channel or group link.',     'telegram, messaging', 17),
	(69, 'WhatsApp', 'whatsapp', 'WhatsApp group or direct message link.',   'whatsapp, messaging', 17),
	(70, 'Slack',    'slack',    'Workspace or community Slack invite.',     'slack, community',    17),
	(71, 'GitHub',  'github',  'Git repository hosting and open-source collaboration.', 'github, dev',  18),
	(72, 'GitLab',  'gitlab',  'DevOps and repository platform.',                       'gitlab, dev',  18),
	(73, 'CodePen', 'codepen', 'Online code editor and front-end showcase.',            'codepen, dev', 18),
	(74, 'Medium',     'medium',     'Online publishing platform for articles and essays.', 'medium, writing',      19),
	(75, 'Substack',   'substack',   'Newsletter and subscription writing platform.',       'substack, newsletter', 19),
	(76, 'Newsletter', 'newsletter', 'Direct email newsletter or mailing list link.',       'newsletter, email',    19),
	(77, 'Steam',   'steam',   'PC gaming platform by Valve.',                 'steam, games',  20),
	(78, 'itch.io', 'itch_io', 'Indie game marketplace and creator platform.', 'itchio, games', 20),
	(79, 'Reddit',  'reddit',  'Community-driven social news and discussion platform.', 'reddit, social', 9)
ON CONFLICT ("LinkCategoryID") DO NOTHING;

-- ============================================================
-- Phase 5: ExternalLinks Updates
-- ============================================================

ALTER TABLE "ExternalLinks"
	ADD COLUMN IF NOT EXISTS "LinkCategoryID" integer;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_ExternalLinks_LinkCategories_LinkCategoryID') THEN
		ALTER TABLE "ExternalLinks"
			ADD CONSTRAINT "FK_ExternalLinks_LinkCategories_LinkCategoryID"
			FOREIGN KEY ("LinkCategoryID") REFERENCES "LinkCategories" ("LinkCategoryID")
			ON DELETE RESTRICT;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_ExternalLinks_LinkCategoryID"
	ON "ExternalLinks" ("LinkCategoryID")
	WHERE "LinkCategoryID" IS NOT NULL;

-- Backfill seed rows: Reddit=79, Facebook=27, Instagram=24, Personal Website=21
UPDATE "ExternalLinks" SET "LinkCategoryID" = 79 WHERE "ExternalLinkID" IN (1, 4, 7);
UPDATE "ExternalLinks" SET "LinkCategoryID" = 27 WHERE "ExternalLinkID" IN (2, 8);
UPDATE "ExternalLinks" SET "LinkCategoryID" = 24 WHERE "ExternalLinkID" IN (3, 6, 9);
UPDATE "ExternalLinks" SET "LinkCategoryID" = 21 WHERE "ExternalLinkID" = 5;

-- Drop legacy column (run after backfill is confirmed correct)
-- ALTER TABLE "ExternalLinks" DROP COLUMN IF EXISTS "ServiceName";


-- ============================================================
-- Phase 6: Linker Metadata Normalization
-- ============================================================
-- Ensure MakePublic is derived from contact IsPrivate (source of truth).
-- Remove duplicate fields from DynaForm metadata.
-- Re-sequence field order for consistency.

BEGIN;

ALTER TABLE IF EXISTS "Linker_EntityToContacts"
	DROP COLUMN IF EXISTS "IsPrimary";

-- Keep linker MakePublic for efficient public queries,
-- but derive it from contact privacy so source-of-truth is IsPrivate.
UPDATE "Linker_EntityToContacts" l
SET "MakePublic" = NOT COALESCE(c."IsPrivate", FALSE)
FROM "Contacts" c
WHERE c."ContactID" = l."ContactID";

-- Remove duplicate fields from DynaForm metadata if present.
DELETE FROM "Forms_Fields"
WHERE "Forms_MetadataID" = 901
  AND "Name" IN ('makePublic', 'isPrimary');

-- Re-sequence field order for ManageContactForm1.
WITH reordered AS (
	SELECT
		"Forms_FieldID",
		ROW_NUMBER() OVER (ORDER BY "FieldOrder", "Forms_FieldID") AS new_order
	FROM "Forms_Fields"
	WHERE "Forms_MetadataID" = 901
)
UPDATE "Forms_Fields" ff
SET "FieldOrder" = reordered.new_order
FROM reordered
WHERE ff."Forms_FieldID" = reordered."Forms_FieldID";

COMMIT;

-- ============================================================
-- Phase 7: Unified Primary Contact Migration
-- ============================================================
-- Consolidate split PrimaryAddressID + PrimaryPhoneContactID 
-- into single PrimaryContactID FK on all entities.
-- Backfill from legacy columns; retire split columns from Artist/User/Vendor.
-- Venue retains legacy AddressID + PhoneContactID for backward compatibility.

BEGIN;

-- 1) Add PrimaryContactID columns (idempotent)
ALTER TABLE "Artists"
	ADD COLUMN IF NOT EXISTS "PrimaryContactID" integer;

ALTER TABLE "Users"
	ADD COLUMN IF NOT EXISTS "PrimaryContactID" integer;

ALTER TABLE "Vendors"
	ADD COLUMN IF NOT EXISTS "PrimaryContactID" integer;

ALTER TABLE "Venues"
	ADD COLUMN IF NOT EXISTS "PrimaryContactID" integer;

-- 2) Add FK constraints to Contacts (idempotent)
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_Artists_Contacts_PrimaryContactID') THEN
		ALTER TABLE "Artists"
			ADD CONSTRAINT "FK_Artists_Contacts_PrimaryContactID"
			FOREIGN KEY ("PrimaryContactID") REFERENCES "Contacts" ("ContactID")
			ON DELETE RESTRICT;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_Users_Contacts_PrimaryContactID') THEN
		ALTER TABLE "Users"
			ADD CONSTRAINT "FK_Users_Contacts_PrimaryContactID"
			FOREIGN KEY ("PrimaryContactID") REFERENCES "Contacts" ("ContactID")
			ON DELETE RESTRICT;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_Vendors_Contacts_PrimaryContactID') THEN
		ALTER TABLE "Vendors"
			ADD CONSTRAINT "FK_Vendors_Contacts_PrimaryContactID"
			FOREIGN KEY ("PrimaryContactID") REFERENCES "Contacts" ("ContactID")
			ON DELETE RESTRICT;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_Venues_Contacts_PrimaryContactID') THEN
		ALTER TABLE "Venues"
			ADD CONSTRAINT "FK_Venues_Contacts_PrimaryContactID"
			FOREIGN KEY ("PrimaryContactID") REFERENCES "Contacts" ("ContactID")
			ON DELETE RESTRICT;
	END IF;
END $$;

-- 3) Indexes for PrimaryContactID (idempotent)
CREATE INDEX IF NOT EXISTS "IX_Artists_PrimaryContactID"
	ON "Artists" ("PrimaryContactID")
	WHERE "PrimaryContactID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Users_PrimaryContactID"
	ON "Users" ("PrimaryContactID")
	WHERE "PrimaryContactID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Vendors_PrimaryContactID"
	ON "Vendors" ("PrimaryContactID")
	WHERE "PrimaryContactID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Venues_PrimaryContactID"
	ON "Venues" ("PrimaryContactID")
	WHERE "PrimaryContactID" IS NOT NULL;

-- 4) Backfill PrimaryContactID from legacy split primary fields where present.
-- Preference order: primary phone contact first, then primary address.
-- (Only runs if legacy columns exist; safe for first-time runs on fresh schemas.)

DO $$
BEGIN
	-- Check if legacy PrimaryPhoneContactID column exists on Artists
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Artists' AND column_name = 'PrimaryPhoneContactID'
	) THEN
		UPDATE "Artists" a
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE a."PrimaryContactID" IS NULL
		  AND a."PrimaryPhoneContactID" IS NOT NULL
		  AND c."ContactType" = 'phone'
		  AND c."PhoneContactID" = a."PrimaryPhoneContactID";
	END IF;
END $$;

DO $$
BEGIN
	-- Check if legacy PrimaryAddressID column exists on Artists
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Artists' AND column_name = 'PrimaryAddressID'
	) THEN
		UPDATE "Artists" a
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE a."PrimaryContactID" IS NULL
		  AND a."PrimaryAddressID" IS NOT NULL
		  AND c."ContactType" = 'address'
		  AND c."AddressID" = a."PrimaryAddressID";
	END IF;
END $$;

DO $$
BEGIN
	-- Check if legacy PrimaryPhoneContactID column exists on Users
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Users' AND column_name = 'PrimaryPhoneContactID'
	) THEN
		UPDATE "Users" u
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE u."PrimaryContactID" IS NULL
		  AND u."PrimaryPhoneContactID" IS NOT NULL
		  AND c."ContactType" = 'phone'
		  AND c."PhoneContactID" = u."PrimaryPhoneContactID";
	END IF;
END $$;

DO $$
BEGIN
	-- Check if legacy PrimaryAddressID column exists on Users
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Users' AND column_name = 'PrimaryAddressID'
	) THEN
		UPDATE "Users" u
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE u."PrimaryContactID" IS NULL
		  AND u."PrimaryAddressID" IS NOT NULL
		  AND c."ContactType" = 'address'
		  AND c."AddressID" = u."PrimaryAddressID";
	END IF;
END $$;

DO $$
BEGIN
	-- Check if legacy PrimaryPhoneContactID column exists on Vendors
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Vendors' AND column_name = 'PrimaryPhoneContactID'
	) THEN
		UPDATE "Vendors" v
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE v."PrimaryContactID" IS NULL
		  AND v."PrimaryPhoneContactID" IS NOT NULL
		  AND c."ContactType" = 'phone'
		  AND c."PhoneContactID" = v."PrimaryPhoneContactID";
	END IF;
END $$;

DO $$
BEGIN
	-- Check if legacy PrimaryAddressID column exists on Vendors
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Vendors' AND column_name = 'PrimaryAddressID'
	) THEN
		UPDATE "Vendors" v
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE v."PrimaryContactID" IS NULL
		  AND v."PrimaryAddressID" IS NOT NULL
		  AND c."ContactType" = 'address'
		  AND c."AddressID" = v."PrimaryAddressID";
	END IF;
END $$;

DO $$
BEGIN
	-- Venue: Backfill PrimaryContactID from existing PhoneContactID
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Venues' AND column_name = 'PhoneContactID'
	) THEN
		UPDATE "Venues" v
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE v."PrimaryContactID" IS NULL
		  AND v."PhoneContactID" IS NOT NULL
		  AND c."ContactType" = 'phone'
		  AND c."PhoneContactID" = v."PhoneContactID";
	END IF;
END $$;

DO $$
BEGIN
	-- Venue: Backfill PrimaryContactID from existing AddressID
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Venues' AND column_name = 'AddressID'
	) THEN
		UPDATE "Venues" v
		SET "PrimaryContactID" = c."ContactID"
		FROM "Contacts" c
		WHERE v."PrimaryContactID" IS NULL
		  AND v."AddressID" IS NOT NULL
		  AND c."ContactType" = 'address'
		  AND c."AddressID" = v."AddressID";
	END IF;
END $$;

-- 5) Retire legacy split-primary columns for entities now using PrimaryContactID.
-- (Only drops columns if they exist; safe for schemas that never had them.)

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Artists' AND column_name = 'PrimaryAddressID'
	) THEN
		ALTER TABLE "Artists"
			DROP COLUMN "PrimaryAddressID";
	END IF;
END $$;

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Artists' AND column_name = 'PrimaryPhoneContactID'
	) THEN
		ALTER TABLE "Artists"
			DROP COLUMN "PrimaryPhoneContactID";
	END IF;
END $$;

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Users' AND column_name = 'PrimaryAddressID'
	) THEN
		ALTER TABLE "Users"
			DROP COLUMN "PrimaryAddressID";
	END IF;
END $$;

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Users' AND column_name = 'PrimaryPhoneContactID'
	) THEN
		ALTER TABLE "Users"
			DROP COLUMN "PrimaryPhoneContactID";
	END IF;
END $$;

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Vendors' AND column_name = 'PrimaryAddressID'
	) THEN
		ALTER TABLE "Vendors"
			DROP COLUMN "PrimaryAddressID";
	END IF;
END $$;

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'Vendors' AND column_name = 'PrimaryPhoneContactID'
	) THEN
		ALTER TABLE "Vendors"
			DROP COLUMN "PrimaryPhoneContactID";
	END IF;
END $$;

COMMIT;

-- ============================================================
-- MIGRATION COMPLETE
-- ============================================================
-- This consolidated final-state script captures all end-state changes
-- needed to migrate from split-primary to unified-contact model.
--
-- Summary of Changes:
-- ✓ Phase 1: Phone contact infrastructure (labels, defaults)
-- ✓ Phase 2: Privacy flags (IsPrivate) on core entities
-- ✓ Phase 3: Unified Contact table (wraps address/phone/email/url)
-- ✓ Phase 4: Linker_EntityToContacts junction table
-- ✓ Phase 4.5: LinkCategories hierarchy (79 platform categories)
-- ✓ Phase 5: ExternalLinks updated with LinkCategoryID FK
-- ✓ Phase 6: Linker metadata normalization (MakePublic sync, form cleanup)
-- ✓ Phase 7: PrimaryContactID migration & legacy column retirement
--
-- All DDL is idempotent; safe to run multiple times.
-- All operations in transactions where semantically appropriate.
--
-- To run on restored production database:
--   psql -d tag_web_db -f 116_contact_refactor.sql
-- ============================================================

-- ============================================================
-- Phase 8: Shared Contact Labels Delta (Post-Refactor Addendum)
-- ============================================================
-- Purpose:
--   Introduce a single shared ContactLabels table and wire it to
--   Contacts, Addresses, PhoneContacts, and ExternalLinks.
--
-- Notes:
--   - Idempotent and safe to run multiple times.
--   - Keeps legacy PhoneContactLabels in place for compatibility.
--   - Backfills where deterministic label mapping is available.

BEGIN;

CREATE TABLE IF NOT EXISTS "ContactLabels" (
	"ContactLabelID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"Label" varchar(100) NOT NULL,
	CONSTRAINT "AK_ContactLabels_Label" UNIQUE ("Label")
);

INSERT INTO "ContactLabels" ("ContactLabelID", "Label")
VALUES
	(1, 'home'),
	(2, 'work'),
	(3, 'mobile'),
	(4, 'office'),
	(5, 'studio'),
	(6, 'regional office'),
	(7, 'support'),
	(8, 'booking'),
	(9, 'press'),
	(10, 'billing'),
	(11, 'sales'),
	(12, 'hq'),
	(13, 'warehouse'),
	(14, 'branch'),
	(15, 'other')
ON CONFLICT ("ContactLabelID") DO NOTHING;

ALTER TABLE "Contacts"
	ADD COLUMN IF NOT EXISTS "ContactLabelID" integer;

ALTER TABLE "Addresses"
	ADD COLUMN IF NOT EXISTS "ContactLabelID" integer;

ALTER TABLE "PhoneContacts"
	ADD COLUMN IF NOT EXISTS "ContactLabelID" integer;

ALTER TABLE "ExternalLinks"
	ADD COLUMN IF NOT EXISTS "ContactLabelID" integer;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_Contacts_ContactLabels_ContactLabelID') THEN
		ALTER TABLE "Contacts"
			ADD CONSTRAINT "FK_Contacts_ContactLabels_ContactLabelID"
			FOREIGN KEY ("ContactLabelID") REFERENCES "ContactLabels" ("ContactLabelID")
			ON DELETE RESTRICT;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_Addresses_ContactLabels_ContactLabelID') THEN
		ALTER TABLE "Addresses"
			ADD CONSTRAINT "FK_Addresses_ContactLabels_ContactLabelID"
			FOREIGN KEY ("ContactLabelID") REFERENCES "ContactLabels" ("ContactLabelID")
			ON DELETE RESTRICT;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_PhoneContacts_ContactLabels_ContactLabelID') THEN
		ALTER TABLE "PhoneContacts"
			ADD CONSTRAINT "FK_PhoneContacts_ContactLabels_ContactLabelID"
			FOREIGN KEY ("ContactLabelID") REFERENCES "ContactLabels" ("ContactLabelID")
			ON DELETE RESTRICT;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint
		WHERE conname = 'FK_ExternalLinks_ContactLabels_ContactLabelID') THEN
		ALTER TABLE "ExternalLinks"
			ADD CONSTRAINT "FK_ExternalLinks_ContactLabels_ContactLabelID"
			FOREIGN KEY ("ContactLabelID") REFERENCES "ContactLabels" ("ContactLabelID")
			ON DELETE RESTRICT;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Contacts_ContactLabelID"
	ON "Contacts" ("ContactLabelID")
	WHERE "ContactLabelID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Addresses_ContactLabelID"
	ON "Addresses" ("ContactLabelID")
	WHERE "ContactLabelID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_PhoneContacts_ContactLabelID"
	ON "PhoneContacts" ("ContactLabelID")
	WHERE "ContactLabelID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_ExternalLinks_ContactLabelID"
	ON "ExternalLinks" ("ContactLabelID")
	WHERE "ContactLabelID" IS NOT NULL;

-- New API flow allows PhoneContactLabelID to be null during transition.
ALTER TABLE "PhoneContacts"
	ALTER COLUMN "PhoneContactLabelID" DROP NOT NULL;

-- Backfill Contacts from existing Contact.Label text when possible.
UPDATE "Contacts" c
SET "ContactLabelID" = cl."ContactLabelID"
FROM "ContactLabels" cl
WHERE c."ContactLabelID" IS NULL
	AND c."Label" IS NOT NULL
	AND LOWER(TRIM(c."Label")) = LOWER(TRIM(cl."Label"));

-- Backfill PhoneContacts via legacy PhoneContactLabels mapping.
UPDATE "PhoneContacts" pc
SET "ContactLabelID" = cl."ContactLabelID"
FROM "PhoneContactLabels" pcl
JOIN "ContactLabels" cl
	ON LOWER(TRIM(cl."Label")) = LOWER(TRIM(pcl."Label"))
WHERE pc."ContactLabelID" IS NULL
	AND pc."PhoneContactLabelID" = pcl."PhoneContactLabelID";

-- Backfill Address labels from linked address-type Contacts when deterministic.
UPDATE "Addresses" a
SET "ContactLabelID" = src."ContactLabelID"
FROM (
	SELECT DISTINCT c."AddressID", c."ContactLabelID"
	FROM "Contacts" c
	WHERE c."ContactType" = 'address'
		AND c."AddressID" IS NOT NULL
		AND c."ContactLabelID" IS NOT NULL
) src
WHERE a."ContactLabelID" IS NULL
	AND a."AddressID" = src."AddressID";

COMMIT;

