-- Run this script against the TAG database after backing up.
-- Purpose: create DB-backed bug report tables and relationships used by FE-148 bug report flow.

BEGIN;

CREATE TABLE IF NOT EXISTS "BugReport"
(
	"BugReportID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"UserID" integer NULL,
	"ReporterEmail" character varying(250) NULL,
	"ShortDescription" character varying(180) NOT NULL,
	"ExpectedBehavior" character varying(1200) NOT NULL,
	"LongDescription" character varying(4000) NOT NULL,
	"SessionContext" text NULL,
	"BuildNumber" character varying(200) NULL,
	"PageContext" text NULL,
	"Diagnostics" text NULL,
	"Status" character varying(50) NOT NULL DEFAULT 'new',
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'FK_BugReport_Users_UserID') THEN
		ALTER TABLE "BugReport"
			ADD CONSTRAINT "FK_BugReport_Users_UserID"
			FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID")
			ON DELETE SET NULL;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_BugReport_Status"
	ON "BugReport" ("Status");

CREATE INDEX IF NOT EXISTS "IX_BugReport_CreatedAt"
	ON "BugReport" ("CreatedAt");

CREATE INDEX IF NOT EXISTS "IX_BugReport_UserID"
	ON "BugReport" ("UserID");

CREATE TABLE IF NOT EXISTS "BugReportStaffNote"
(
	"BugReportStaffNoteID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"BugReportID" integer NOT NULL,
	"StaffID" integer NULL,
	"Note" character varying(4000) NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'FK_BugReportStaffNote_BugReport_BugReportID') THEN
		ALTER TABLE "BugReportStaffNote"
			ADD CONSTRAINT "FK_BugReportStaffNote_BugReport_BugReportID"
			FOREIGN KEY ("BugReportID") REFERENCES "BugReport" ("BugReportID")
			ON DELETE CASCADE;
	END IF;
END $$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'FK_BugReportStaffNote_Staffs_StaffID') THEN
		ALTER TABLE "BugReportStaffNote"
			ADD CONSTRAINT "FK_BugReportStaffNote_Staffs_StaffID"
			FOREIGN KEY ("StaffID") REFERENCES "Staffs" ("StaffID")
			ON DELETE SET NULL;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_BugReportStaffNote_BugReportID"
	ON "BugReportStaffNote" ("BugReportID");

CREATE INDEX IF NOT EXISTS "IX_BugReportStaffNote_CreatedAt"
	ON "BugReportStaffNote" ("CreatedAt");

COMMIT;

