-- ============================================================
-- Media Metadata and Credits Foundation (Issues #86, #90)
-- ============================================================
-- Purpose:
--   - Keep Pictures and extend metadata support.
--   - Add Videos as peer media records.
--   - Add scoped Galleries with ordered mixed media items.
--   - Add credits module for linked users/artists and external parties.
--   - Support credits on pictures, videos, and blogs.
--
-- Notes:
--   - Idempotent-first where practical (IF NOT EXISTS / guarded constraints).
--   - This script is for alpha modeling; EF migrations remain source of truth.
-- ============================================================

-- Picture metadata extensions.
ALTER TABLE "Pictures"
	ADD COLUMN IF NOT EXISTS "NormalizedURL" text,
	ADD COLUMN IF NOT EXISTS "Byline" varchar(2000),
	ADD COLUMN IF NOT EXISTS "Updated" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "IX_Pictures_NormalizedURL"
	ON "Pictures" ("NormalizedURL");

-- Peer media entity: Videos.
CREATE TABLE IF NOT EXISTS "Videos" (
	"VideoID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"UserID" integer,
	"ArtistID" integer,
	"Title" varchar(1000),
	"Byline" varchar(2000),
	"Description" text,
	"EmbedURL" text NOT NULL,
	"URL" text,
	"ThumbnailURL" text,
	"Provider" varchar(40) NOT NULL DEFAULT 'vimeo',
	"ProviderVideoID" varchar(200),
	"NormalizedEmbedURL" text,
	"Created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"Updated" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "FK_Videos_Users_UserID"
		FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE SET NULL,
	CONSTRAINT "FK_Videos_Artists_ArtistID"
		FOREIGN KEY ("ArtistID") REFERENCES "Artists" ("ArtistID") ON DELETE SET NULL,
	CONSTRAINT "CK_Video_Provider"
		CHECK ("Provider" IN ('vimeo', 'youtube'))
);

CREATE INDEX IF NOT EXISTS "IX_Videos_NormalizedEmbedURL"
	ON "Videos" ("NormalizedEmbedURL");

-- Scoped galleries (entity scope + owner).
CREATE TABLE IF NOT EXISTS "Galleries" (
	"GalleryID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"ScopeType" varchar(100) NOT NULL,
	"ScopeEntityID" integer NOT NULL,
	"OwnerUserID" integer,
	"OwnerArtistID" integer,
	"Title" varchar(250),
	"Description" text,
	"IsPrimary" boolean NOT NULL DEFAULT FALSE,
	"Created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"Updated" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "FK_Galleries_Users_OwnerUserID"
		FOREIGN KEY ("OwnerUserID") REFERENCES "Users" ("UserID") ON DELETE SET NULL,
	CONSTRAINT "FK_Galleries_Artists_OwnerArtistID"
		FOREIGN KEY ("OwnerArtistID") REFERENCES "Artists" ("ArtistID") ON DELETE SET NULL,
	CONSTRAINT "CK_Gallery_SingleOwner"
		CHECK ((CASE WHEN "OwnerUserID" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN "OwnerArtistID" IS NOT NULL THEN 1 ELSE 0 END) <= 1)
);

CREATE INDEX IF NOT EXISTS "IX_Galleries_ScopeType_ScopeEntityID"
	ON "Galleries" ("ScopeType", "ScopeEntityID");

-- Entity-level gallery and banner/profile picture links.
ALTER TABLE "Blogs"
	ADD COLUMN IF NOT EXISTS "GalleryID" integer,
	ADD COLUMN IF NOT EXISTS "CoverPicID" integer;

ALTER TABLE "Events"
	ADD COLUMN IF NOT EXISTS "GalleryID" integer,
	ADD COLUMN IF NOT EXISTS "CoverPicID" integer,
	ADD COLUMN IF NOT EXISTS "ProfilePicID" integer;

ALTER TABLE "Users"
	ADD COLUMN IF NOT EXISTS "GalleryID" integer,
	ADD COLUMN IF NOT EXISTS "CoverPicID" integer,
	ADD COLUMN IF NOT EXISTS "ProfilePicID" integer;

ALTER TABLE "Artists"
	ADD COLUMN IF NOT EXISTS "GalleryID" integer;

ALTER TABLE "Listings"
	ADD COLUMN IF NOT EXISTS "GalleryID" integer,
	ADD COLUMN IF NOT EXISTS "CoverPicID" integer;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Blogs_Galleries_GalleryID') THEN
		ALTER TABLE "Blogs" ADD CONSTRAINT "FK_Blogs_Galleries_GalleryID"
			FOREIGN KEY ("GalleryID") REFERENCES "Galleries" ("GalleryID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Blogs_Pictures_CoverPicID') THEN
		ALTER TABLE "Blogs" ADD CONSTRAINT "FK_Blogs_Pictures_CoverPicID"
			FOREIGN KEY ("CoverPicID") REFERENCES "Pictures" ("PictureID") ON DELETE SET NULL;
	END IF;

	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Events_Galleries_GalleryID') THEN
		ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Galleries_GalleryID"
			FOREIGN KEY ("GalleryID") REFERENCES "Galleries" ("GalleryID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Events_Pictures_CoverPicID') THEN
		ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Pictures_CoverPicID"
			FOREIGN KEY ("CoverPicID") REFERENCES "Pictures" ("PictureID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Events_Pictures_ProfilePicID') THEN
		ALTER TABLE "Events" ADD CONSTRAINT "FK_Events_Pictures_ProfilePicID"
			FOREIGN KEY ("ProfilePicID") REFERENCES "Pictures" ("PictureID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Galleries_GalleryID') THEN
		ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Galleries_GalleryID"
			FOREIGN KEY ("GalleryID") REFERENCES "Galleries" ("GalleryID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Pictures_CoverPicID') THEN
		ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Pictures_CoverPicID"
			FOREIGN KEY ("CoverPicID") REFERENCES "Pictures" ("PictureID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Users_Pictures_ProfilePicID') THEN
		ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Pictures_ProfilePicID"
			FOREIGN KEY ("ProfilePicID") REFERENCES "Pictures" ("PictureID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Artists_Galleries_GalleryID') THEN
		ALTER TABLE "Artists" ADD CONSTRAINT "FK_Artists_Galleries_GalleryID"
			FOREIGN KEY ("GalleryID") REFERENCES "Galleries" ("GalleryID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Listings_Galleries_GalleryID') THEN
		ALTER TABLE "Listings" ADD CONSTRAINT "FK_Listings_Galleries_GalleryID"
			FOREIGN KEY ("GalleryID") REFERENCES "Galleries" ("GalleryID") ON DELETE SET NULL;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Listings_Pictures_CoverPicID') THEN
		ALTER TABLE "Listings" ADD CONSTRAINT "FK_Listings_Pictures_CoverPicID"
			FOREIGN KEY ("CoverPicID") REFERENCES "Pictures" ("PictureID") ON DELETE SET NULL;
	END IF;

END $$;

CREATE INDEX IF NOT EXISTS "IX_Blogs_GalleryID" ON "Blogs" ("GalleryID");
CREATE INDEX IF NOT EXISTS "IX_Blogs_CoverPicID" ON "Blogs" ("CoverPicID");

CREATE INDEX IF NOT EXISTS "IX_Events_GalleryID" ON "Events" ("GalleryID");
CREATE INDEX IF NOT EXISTS "IX_Events_CoverPicID" ON "Events" ("CoverPicID");
CREATE INDEX IF NOT EXISTS "IX_Events_ProfilePicID" ON "Events" ("ProfilePicID");

CREATE INDEX IF NOT EXISTS "IX_Users_GalleryID" ON "Users" ("GalleryID");
CREATE INDEX IF NOT EXISTS "IX_Users_CoverPicID" ON "Users" ("CoverPicID");
CREATE INDEX IF NOT EXISTS "IX_Users_ProfilePicID" ON "Users" ("ProfilePicID");

CREATE INDEX IF NOT EXISTS "IX_Artists_GalleryID" ON "Artists" ("GalleryID");

CREATE INDEX IF NOT EXISTS "IX_Listings_GalleryID" ON "Listings" ("GalleryID");
CREATE INDEX IF NOT EXISTS "IX_Listings_CoverPicID" ON "Listings" ("CoverPicID");

-- Ordered mixed media linker: gallery items.
CREATE TABLE IF NOT EXISTS "GalleryItems" (
	"GalleryItemID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"GalleryID" integer NOT NULL,
	"PictureID" integer,
	"VideoID" integer,
	"SortOrder" integer NOT NULL DEFAULT 0,
	"CaptionOverride" text,
	"AddedByUserID" integer,
	"Created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "FK_GalleryItems_Galleries_GalleryID"
		FOREIGN KEY ("GalleryID") REFERENCES "Galleries" ("GalleryID") ON DELETE CASCADE,
	CONSTRAINT "FK_GalleryItems_Pictures_PictureID"
		FOREIGN KEY ("PictureID") REFERENCES "Pictures" ("PictureID") ON DELETE CASCADE,
	CONSTRAINT "FK_GalleryItems_Videos_VideoID"
		FOREIGN KEY ("VideoID") REFERENCES "Videos" ("VideoID") ON DELETE CASCADE,
	CONSTRAINT "FK_GalleryItems_Users_AddedByUserID"
		FOREIGN KEY ("AddedByUserID") REFERENCES "Users" ("UserID") ON DELETE SET NULL,
	CONSTRAINT "CK_GalleryItem_ExactlyOneMedia"
		CHECK ((CASE WHEN "PictureID" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN "VideoID" IS NOT NULL THEN 1 ELSE 0 END) = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GalleryItems_GalleryID_SortOrder"
	ON "GalleryItems" ("GalleryID", "SortOrder");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GalleryItems_GalleryID_PictureID"
	ON "GalleryItems" ("GalleryID", "PictureID")
	WHERE "PictureID" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GalleryItems_GalleryID_VideoID"
	ON "GalleryItems" ("GalleryID", "VideoID")
	WHERE "VideoID" IS NOT NULL;

-- Credits reference data.
CREATE TABLE IF NOT EXISTS "CreditRoles" (
	"CreditRoleID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"KeyName" varchar(120) NOT NULL,
	"Label" varchar(200) NOT NULL,
	"DisplayOrder" integer NOT NULL DEFAULT 0,
	"IsActive" boolean NOT NULL DEFAULT TRUE,
	CONSTRAINT "AK_CreditRoles_KeyName" UNIQUE ("KeyName")
);

INSERT INTO "CreditRoles" ("CreditRoleID", "KeyName", "Label", "DisplayOrder", "IsActive")
VALUES
	(1, 'copyright_owner', 'Copyright Owner', 1, TRUE),
	(2, 'photographer', 'Photographer', 2, TRUE),
	(3, 'videographer', 'Videographer', 3, TRUE),
	(4, 'makeup', 'Makeup', 4, TRUE),
	(5, 'set', 'Set Design', 5, TRUE),
	(6, 'design', 'Design', 6, TRUE),
	(7, 'tech', 'Tech / Stage', 7, TRUE),
	(8, 'lighting', 'Lighting', 8, TRUE),
	(9, 'audio', 'Audio', 9, TRUE),
	(10, 'editor', 'Editor', 10, TRUE),
	(11, 'producer', 'Producer', 11, TRUE),
	(12, 'assistant', 'Assistant', 12, TRUE),
	(13, 'stylist', 'Stylist', 13, TRUE),
	(14, 'wardrobe', 'Wardrobe', 14, TRUE),
	(15, 'model', 'Model', 15, TRUE)
ON CONFLICT ("CreditRoleID") DO NOTHING;

-- Credit parties: account-linked or external collaborators.
CREATE TABLE IF NOT EXISTS "CreditParties" (
	"CreditPartyID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"UserID" integer,
	"ArtistID" integer,
	"DisplayName" varchar(250),
	"ExternalURL" text,
	"BioNote" varchar(2000),
	"Created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "FK_CreditParties_Users_UserID"
		FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID") ON DELETE SET NULL,
	CONSTRAINT "FK_CreditParties_Artists_ArtistID"
		FOREIGN KEY ("ArtistID") REFERENCES "Artists" ("ArtistID") ON DELETE SET NULL,
	CONSTRAINT "CK_CreditParty_HasIdentity"
		CHECK (
			(CASE WHEN "UserID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "ArtistID" IS NOT NULL THEN 1 ELSE 0 END +
			 CASE WHEN "DisplayName" IS NOT NULL AND LENGTH(TRIM("DisplayName")) > 0 THEN 1 ELSE 0 END) >= 1
		)
);

-- Media-to-credit assignments (pictures, videos, and blogs).
CREATE TABLE IF NOT EXISTS "MediaCredits" (
	"MediaCreditID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"PictureID" integer,
	"VideoID" integer,
	"BlogID" integer,
	"CreditPartyID" integer NOT NULL,
	"CreditRoleID" integer NOT NULL,
	"CreditText" varchar(2000),
	"SortOrder" integer NOT NULL DEFAULT 0,
	CONSTRAINT "FK_MediaCredits_Pictures_PictureID"
		FOREIGN KEY ("PictureID") REFERENCES "Pictures" ("PictureID") ON DELETE CASCADE,
	CONSTRAINT "FK_MediaCredits_Videos_VideoID"
		FOREIGN KEY ("VideoID") REFERENCES "Videos" ("VideoID") ON DELETE CASCADE,
	CONSTRAINT "FK_MediaCredits_Blogs_BlogID"
		FOREIGN KEY ("BlogID") REFERENCES "Blogs" ("BlogID") ON DELETE CASCADE,
	CONSTRAINT "FK_MediaCredits_CreditParties_CreditPartyID"
		FOREIGN KEY ("CreditPartyID") REFERENCES "CreditParties" ("CreditPartyID") ON DELETE CASCADE,
	CONSTRAINT "FK_MediaCredits_CreditRoles_CreditRoleID"
		FOREIGN KEY ("CreditRoleID") REFERENCES "CreditRoles" ("CreditRoleID") ON DELETE RESTRICT,
	CONSTRAINT "CK_MediaCredit_ExactlyOneMedia"
		CHECK ((CASE WHEN "PictureID" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN "VideoID" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN "BlogID" IS NOT NULL THEN 1 ELSE 0 END) = 1)
);

-- Idempotent upgrade path for existing databases that may have pre-blog MediaCredits.
ALTER TABLE "MediaCredits"
	ADD COLUMN IF NOT EXISTS "BlogID" integer;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MediaCredits_Blogs_BlogID') THEN
		ALTER TABLE "MediaCredits" ADD CONSTRAINT "FK_MediaCredits_Blogs_BlogID"
			FOREIGN KEY ("BlogID") REFERENCES "Blogs" ("BlogID") ON DELETE CASCADE;
	END IF;

	IF EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'CK_MediaCredit_ExactlyOneMedia'
		  AND conrelid = '"MediaCredits"'::regclass
	) THEN
		ALTER TABLE "MediaCredits" DROP CONSTRAINT "CK_MediaCredit_ExactlyOneMedia";
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'CK_MediaCredit_ExactlyOneMedia'
		  AND conrelid = '"MediaCredits"'::regclass
	) THEN
		ALTER TABLE "MediaCredits" ADD CONSTRAINT "CK_MediaCredit_ExactlyOneMedia"
			CHECK ((CASE WHEN "PictureID" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN "VideoID" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN "BlogID" IS NOT NULL THEN 1 ELSE 0 END) = 1);
	END IF;
END $$;

-- Unique constraints per media type (filtered indexes for non-NULL media).
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MediaCredits_PictureID_CreditPartyID_CreditRoleID"
	ON "MediaCredits" ("PictureID", "CreditPartyID", "CreditRoleID")
	WHERE "PictureID" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MediaCredits_VideoID_CreditPartyID_CreditRoleID"
	ON "MediaCredits" ("VideoID", "CreditPartyID", "CreditRoleID")
	WHERE "VideoID" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MediaCredits_BlogID_CreditPartyID_CreditRoleID"
	ON "MediaCredits" ("BlogID", "CreditPartyID", "CreditRoleID")
	WHERE "BlogID" IS NOT NULL;
